export const UPDATE_SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
export const UPDATE_BOOKMARKS = "UPDATE_BOOKMARKS";
export const ADD_BOOKMARKS = "ADD_BOOKMARKS";
export const UPDATE_DETAIL = "UPDATE_DETAIL";
